spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://mysql-code-dictionary-master:3306/code_dictionary_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    replica:
      jdbc-url: jdbc:mysql://mysql-code-dictionary-master:3306/code_dictionary_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate

opensearch:
  host: opensearch
  port: 9200
