apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: commerce
resources:
  - cronjob-overview.yaml
  - cronjob-intro.yaml
  - cronjob-media.yaml
  - cronjob-links.yaml
  - cronjob-google-places.yaml
  - cronjob-lcls-codes.yaml
  - cronjob-pet-tour.yaml
  - cronjob-tour-sync.yaml
  - cronjob-attraction-attrs.yaml
  - cronjob-visitors.yaml
  - cronjob-weather-short.yaml
  - cronjob-weather-mid.yaml
  - cronjob-congestion.yaml
  - cronjob-related.yaml
  - cronjob-air.yaml
  - cronjob-air-stations.yaml
