spring:
  datasource:
    member:
      master:
        jdbc-url: jdbc:mysql://mysql-member-master:3306/member_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      replica:
        jdbc-url: jdbc:mysql://mysql-member-replica:3306/member_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    wishlist:
      master:
        jdbc-url: jdbc:mysql://mysql-wishlist-master:3306/wishlist_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      replica:
        jdbc-url: jdbc:mysql://mysql-wishlist-replica:3306/wishlist_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  kafka:
    bootstrap-servers: kafka:29092
