apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: commerce
  labels:
    app.kubernetes.io/name: recommendation
    app.kubernetes.io/part-of: commerce-platform
spec:
  selector:
    app.kubernetes.io/name: recommendation
  ports:
    - name: http
      port: 8092
      targetPort: http
