spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://mysql-member-master:3306/member_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    replica:
      jdbc-url: jdbc:mysql://mysql-member-master:3306/member_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

