apiVersion: v1
kind: Service
metadata:
  name: atlas
  namespace: commerce
  labels:
    app.kubernetes.io/name: atlas
    app.kubernetes.io/part-of: commerce-platform
spec:
  selector:
    app.kubernetes.io/name: atlas
  ports:
    - name: http
      port: 8089
      targetPort: http
