apiVersion: v1
kind: Service
metadata:
  name: quant-fe
  namespace: commerce
  labels:
    app.kubernetes.io/name: quant-fe
    app.kubernetes.io/part-of: commerce-platform
spec:
  selector:
    app.kubernetes.io/name: quant-fe
  ports:
    - name: http
      port: 80
      targetPort: http
