include:
  - path: docker-compose.yml

services:

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # 프론트엔드 빌드 결과물 마운트
      - ../gifticon/frontend/dist:/srv/gifticon/dist:ro
      - ../code-dictionary/frontend/dist:/srv/code-dictionary/dist:ro
    depends_on:
      gateway:
        condition: service_started
    networks:
      commerce-network:
        ipv4_address: 172.20.0.2
    restart: unless-stopped
