# docker/backup/config/databases.conf
# FORMAT: db_name|master_host|master_port
# Lines starting with # are ignored

product_db|mysql-product-master|3306
order_db|mysql-order-master|3306
auth_db|mysql-auth-master|3306
gifticon_db|mysql-gifticon-master|3306
code_dictionary_db|mysql-code-dictionary-master|3306
