spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

search:
  ranking:
    popularity-weight: 10.0
    ctr-weight: 5.0
