apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-backup
  namespace: commerce
  labels:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/part-of: commerce-platform
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
