apiVersion: v1
kind: Service
metadata:
  name: amp-arena
  namespace: commerce
  labels:
    app.kubernetes.io/name: amp-arena
    app.kubernetes.io/part-of: commerce-platform
spec:
  selector:
    app.kubernetes.io/name: amp-arena
  ports:
    - name: http
      port: 8787
      targetPort: http
