apiVersion: v1
kind: Service
metadata:
  name: warehouse
  namespace: commerce
  labels:
    app.kubernetes.io/name: warehouse
    app.kubernetes.io/part-of: commerce-platform
spec:
  selector:
    app.kubernetes.io/name: warehouse
  ports:
    - name: http
      port: 8090
      targetPort: http
