apiVersion: v1
kind: Service
metadata:
  name: recommendation-ann
  namespace: commerce
  labels:
    app.kubernetes.io/name: recommendation-ann
    app.kubernetes.io/part-of: commerce-platform
spec:
  selector:
    app.kubernetes.io/name: recommendation-ann
  ports:
    - name: http
      port: 8000
      targetPort: http
