apiVersion: v1
kind: Service
metadata:
  name: fulfillment
  namespace: commerce
  labels:
    app.kubernetes.io/name: fulfillment
    app.kubernetes.io/part-of: commerce-platform
spec:
  selector:
    app.kubernetes.io/name: fulfillment
  ports:
    - name: http
      port: 8088
      targetPort: http
