spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://mysql-warehouse-master:3306/warehouse_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    replica:
      jdbc-url: jdbc:mysql://mysql-warehouse-replica:3306/warehouse_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

