server:
  port: 8090
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
