apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring":{"data":{"redis":{"cluster":null,"host":"redis","port":6379}}}}'
